### ISSUE TITLE
Depending on a vulnerable package 'jsonld.js'

### ISSUE THREAD

**Issue by jcoyne** [rdfjs-base/serializer-jsonld-ext#4]
See https://github.com/digitalbazaar/jsonld.js/issues/457

This would be resolved by upgrading to version 5.2.0 of jsonld.js

**Comment by bergos** [comment]
Thanks for the hint. I fixed it in #5 . You need to upgrade to version 3.0.0. See the details in the PR.

**Comment by jcoyne** [comment]
@bergos Thank you so much!
